SELECT MACT, HOTEN, SO, VITRI, NGAYSINH, DIACHI
FROM CAUTHU

SELECT *
FROM CAUTHU
WHERE SO=7 AND VITRI=N'Tiền vệ'

SELECT TENHLV, NGAYSINH, DIACHI, DIENTHOAI
FROM HUANLUYENVIEN

SELECT CT.*
FROM CAUTHU as CT
JOIN CAULACBO AS CLB ON CT.MACLB = CLB.MACLB
JOIN QUOCGIA AS QG ON CT.MAQG = QG.MAQG
WHERE QG.TENQG = N'Việt Nam'
AND CLB.TENCLB = N'Becamex Bình Dương'


SELECT *
FROM CAUTHU
WHERE MAQG='VN' AND MACLB='BBD'

SELECT CT.SO, CT.HOTEN, CT.NGAYSINH, CT.DIACHI, CT.VITRI
FROM CAUTHU CT
JOIN CAULACBO CLB ON CT.MACLB = CLB.MACLB
JOIN QUOCGIA QG ON CT.MAQG = QG.MAQG
WHERE CLB.TENCLB = N'SHB Đà Nẵng'
AND QG.TENQG = N'Bra-xin'

SELECT CT.*
FROM CAUTHU CT
JOIN CAULACBO CLB ON CT.MACLB = CLB.MACLB
JOIN SANVD S ON CLB.MASAN = S.MASAN
WHERE S.TENSAN = N'Long An'

SELECT TD.MATRAN, TD.NGAYTD, S.TENSAN,
CLB1.TENCLB AS TENCLB1,
CLB2.TENCLB AS TENCLB2,
TD.KETQUA
FROM TRANDAU TD
JOIN SANVD S ON TD.MASAN = S.MASAN
JOIN CAULACBO CLB1 ON TD.MACLB1 = CLB1.MACLB
JOIN CAULACBO CLB2 ON TD.MACLB2 = CLB2.MACLB
WHERE TD.NAM = 2009

SELECT HLV.MAHLV, HLV.TENHLV, HLV.NGAYSINH, HLV.DIACHI, HC.VAITRO, CLB.TENCLB
FROM HUANLUYENVIEN HLV
JOIN HLV_CLB HC ON HLV.MAHLV = HC.MAHLV
JOIN CAULACBO CLB ON HC.MACLB = CLB.MACLB
JOIN QUOCGIA QG ON HLV.MAQG = QG.MAQG
WHERE QG.TENQG = N'Việt Nam'

SELECT TOP 3 *
FROM BANGXH
WHERE NAM = 2009 AND VONG = 3
ORDER BY DIEM DESC

SELECT HLV.MAHLV, HLV.TENHLV, HLV.NGAYSINH, HLV.DIACHI, HC.VAITRO, CLB.TENCLB
FROM HUANLUYENVIEN HLV
JOIN HLV_CLB HC ON HLV.MAHLV = HC.MAHLV
JOIN CAULACBO CLB ON HC.MACLB = CLB.MACLB
JOIN TINH T ON CLB.MATINH = T.MATINH
WHERE T.TENTINH = N'Bình Dương'

SELECT CLB.TENCLB, COUNT(CT.MACT) AS SoLuongCauThu
FROM CAULACBO CLB
LEFT JOIN CAUTHU CT ON CLB.MACLB = CT.MACLB
GROUP BY CLB.TENCLB


SELECT CLB.TENCLB, COUNT(CT.MACT) AS SoCauThuNuocNgoai
FROM CAULACBO CLB
JOIN CAUTHU CT ON CLB.MACLB = CT.MACLB
JOIN QUOCGIA QG ON CT.MAQG = QG.MAQG
WHERE QG.TENQG <> N'Việt Nam'
GROUP BY CLB.TENCLB

SELECT CLB.TENCLB, COUNT(CT.MACT) AS SoCauThuNuocNgoai
FROM CAULACBO CLB
JOIN CAUTHU CT ON CLB.MACLB = CT.MACLB
JOIN QUOCGIA QG ON CT.MAQG = QG.MAQG
WHERE QG.TENQG <> N'Việt Nam'
GROUP BY CLB.TENCLB
HAVING COUNT(CT.MACT) > 2


SELECT T.TENTINH, COUNT(CT.MACT) AS SoTienDao
FROM TINH T
JOIN CAULACBO CLB ON T.MATINH = CLB.MATINH
JOIN CAUTHU CT ON CLB.MACLB = CT.MACLB
WHERE CT.VITRI = N'Tiền đạo'
GROUP BY T.TENTINH


SELECT CLB.TENCLB, T.TENTINH
FROM BANGXH BXH
JOIN CAULACBO CLB ON BXH.MACLB = CLB.MACLB
JOIN TINH T ON CLB.MATINH = T.MATINH
WHERE BXH.NAM = 2009 AND BXH.VONG = 3
AND BXH.HANG = 1

SELECT HLV.TENHLV, HC.VAITRO, CLB.TENCLB
FROM HUANLUYENVIEN HLV
JOIN HLV_CLB HC ON HLV.MAHLV = HC.MAHLV
JOIN CAULACBO CLB ON HC.MACLB = CLB.MACLB
WHERE HLV.DIENTHOAI IS NULL

SELECT TENHLV
FROM HUANLUYENVIEN
WHERE MAQG = (
    SELECT MAQG FROM QUOCGIA WHERE TENQG = N'Việt Nam'
)
AND MAHLV NOT IN (
    SELECT MAHLV FROM HLV_CLB
)

SELECT CT.HOTEN, CLB.TENCLB
FROM CAUTHU CT
JOIN CAULACBO CLB ON CT.MACLB = CLB.MACLB
JOIN BANGXH BXH ON CLB.MACLB = BXH.MACLB
WHERE BXH.NAM = 2009
AND BXH.VONG = 3
AND BXH.HANG BETWEEN 3 AND 6

SELECT TD.NGAYTD, S.TENSAN,
CLB1.TENCLB AS TENCLB1,
CLB2.TENCLB AS TENCLB2,
TD.KETQUA
FROM TRANDAU TD
JOIN SANVD S ON TD.MASAN = S.MASAN
JOIN CAULACBO CLB1 ON TD.MACLB1 = CLB1.MACLB
JOIN CAULACBO CLB2 ON TD.MACLB2 = CLB2.MACLB
WHERE TD.MACLB1 IN (
    SELECT MACLB
    FROM BANGXH
    WHERE NAM = 2009 AND VONG = 3 AND HANG = 1
)
OR TD.MACLB2 IN (
    SELECT MACLB
    FROM BANGXH
    WHERE NAM = 2009 AND VONG = 3 AND HANG = 1
)
